### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Julia-1994** [Julia-1994/Julia-1994.github.io#1]
- [x] 自动生成脚本（自动更新目录，自动编译界面，自动迁移目录）
- [x] 图片单独引入一个 markdown 文件，可以直接在网站中查阅图片
- [x] 使用 mkdocs 压缩插件，减小打包后的 html 体积（本地编译更耗时，所以不推荐使用）
- [x] 尝试改写看板娘插件，使用 Genshin 的图片和背景色（难度较大）——需要图片建模等，暂时不支持

**Comment by Michael18811380328** [comment]
目标：写一个 nodeJS 脚本，然后把对应的路径拼接出来，写入 markdown 文件中

let arr = [];
const path = 'https://julia-1994.github.io/images/Noelle/01.webp';
for (let i = 1; i <= 8; i++) {
  arr[]
}

先遍历全部的项目路径，然后拼接 path, 最后写入 markdown 中，然后 mkdocs 转换成 html 输出

**Comment by Julia-1994** [comment]
资源
https://www.huashi6.com/

**Comment by Michael18811380328** [comment]
https://blog.csdn.net/weixin_44639164/article/details/122216999?spm=1001.2014.3001.5501
